# Test manually triggered workflows with 'workflow_dispatch' triggers
name: Test workflow_dispatch

on:
  # Trigger on pull requests
  pull_request:

  # Manually triggered events
  workflow_dispatch:
    inputs:
      python:
        description: "Python version"
        required: true
        default: "3.14"
        type: string

permissions: {}

jobs:


  test-workflow-dispatch:
    name: Test workflow_dispatch
    runs-on: ubuntu-latest
    env:
      # Use Python 3.14 for any other event different than the workflow_dispatch
      PYTHON: ${{ inputs.python || '3.14' }}

    steps:

      - name: Print Python version
        run: |
          echo "Python version:" ${PYTHON}

